import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Language, translations } from '../translations';

interface LegalPageProps {
  lang: Language;
}

export const LegalPage: React.FC<LegalPageProps & { type: 'imprint' | 'privacy' | 'terms' }> = ({ lang, type }) => {
  const t = translations[lang];
  const navigate = useNavigate();

  const content = {
    imprint: {
      title: t.imprint,
      body: (
        <div className="prose prose-slate max-w-none">
          <h3>Angaben gemäß § 5 TMG</h3>
          <p>[Name des Anbieters/Firma]<br />[Straße und Hausnummer]<br />[Postleitzahl und Ort]</p>
          <h3>Kontakt</h3>
          <p>Telefon: [Telefonnummer]<br />E-Mail: [E-Mail-Adresse]</p>
          <h3>Redaktionell verantwortlich</h3>
          <p>[Name des Verantwortlichen]</p>
        </div>
      )
    },
    privacy: {
      title: t.privacy,
      body: (
        <div className="prose prose-slate max-w-none">
          <p>This application uses PostHog for analytics and Sentry for error tracking if you have given your consent.</p>
          <h3>Analytics</h3>
          <p>We process your IP address and usage behavior to improve the service.</p>
        </div>
      )
    },
    terms: {
      title: t.terms,
      body: (
        <div className="prose prose-slate max-w-none">
          <p>The analysis is generated by AI (Google Gemini). While we strive for accuracy, the information should not be used as the sole basis for decisions.</p>
        </div>
      )
    }
  }[type];

  return (
    <div className="max-w-3xl mx-auto py-12 px-4">
      <button onClick={() => navigate('/')} className="text-blue-600 mb-8 flex items-center gap-2">
        &larr; {t.backToHome}
      </button>
      <h1 className="text-3xl font-bold mb-8">{content.title}</h1>
      <div className="bg-white p-8 rounded-xl shadow-sm border border-gray-100">
        {content.body}
      </div>
    </div>
  );
};
